### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by dawnstrider** [sneakyx/egroupwareserver#1]
When using the given tutorial to start a container, the egroupwarecontainer immediately stops.

This is the result of `docker start -i <name_of_container>`

> chmod: cannot access '/var/lib/egroupware/header.inc.php': No such file or directory

**Comment by helmutundarnold** [comment]
same experience with "latest"

**Comment by sneakyx** [comment]
Hello,
egroupware needs a folder where to put its files. Did you create this folder?

**Comment by helmutundarnold** [comment]
Hi Andre,
yes the folders have create previously.
Just to make sure - with folder you meant to ones that will be mounted  - which are /var/lib/mysql and /var/lib/egroupware right?

**Comment by sneakyx** [comment]
Sorry for late answer.
There was several problems:
1. the mentioned folder rights
2. problems connecting to mysql 8.0 (latest)
See also: https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0/49953657#49953657
Please try again the new version of the script container_control.sh
and let me know if it works with you. For me it worked with my extended version.

**Comment by sneakyx** [comment]
And also try to use the script, the folders will be created and get the right rights.

**Comment by sneakyx** [comment]
Take a look here: https://youtu.be/t3vYX389O4A

**Comment by dawnstrider** [comment]
Thanks for the fix. I am not using the script since I want to replay the actions that were done so I can do some automation of my own. I therefore follow the instructions in the README.MD starting at point 3b.

I re-tested with the current version available from hub.docker.com with the following parameters and result:

*Parameters*
- directories created
- startup calls given as in instructions, modified folder locations accordingly

*Result*
Docker container stops again immediately, *docker start -a egroupware-xxx* gives the following output:
>chmod: cannot access '/var/lib/egroupware/header.inc.php': No such file or directory

My assumption is that there is an instuction missing that the PHP files from the assets directory have to be copied manually?

------
I have following remarks:
- the installation instructions define the folders on the host machine as optional 

> ...it would be wise to create directories for storing everything in place. ...

- I tried to run the container without a SUBFOLDER option. In that case the [docker entrypoint](https://github.com/sneakyx/egroupwareserver/blob/master/assets/docker-entrypoint.sh) file fails at line 61 as it is not set.
- There is an error in the current README.MD, line 41
> Important: /home/egroupware/$2/mysql.cnf create file with following text:

  $2 is an unknown value for the manual installation, going by your script this should be called XXX to be conform to the rest of the instructions.

**Comment by sneakyx** [comment]
Thanks for the remark. You're right, I updated the doc(s). 
But: I don't recommend using own way- or You just copy the lines from script (this is what I've done for updating the docs)
