### ISSUE TITLE
entrypoint script broken

### ISSUE THREAD

**Issue by dawnstrider** [sneakyx/egroupwareserver#2]
**Problem:**

Container with egroupware is not started correctly.

Steps to reproduce:

1. download https://raw.githubusercontent.com/sneakyx/egroupwareserver/master/assets/container_control.sh
2. `chmod +x container_control.sh`
3. `./container_control.sh create egw mypass mypass 4321`
4. `docker ps -a`

**Situation:**

Mysql container is started as expected, egw container is stopped immediately.

Running 
`docker start -a egroupware-egw`

Returns the following output to the console:

> /bin/entrypoint.sh: line 61: [: ==: unary operator expected
> /bin/entrypoint.sh: line 69: syntax error near unexpected token `elif'

**Comment by sneakyx** [comment]
Hi,
thanks for the issue. Can you try again with the update?
Tnx!

**Comment by dawnstrider** [comment]
Retracing my operations from the OP i now only get the following exception:

> /bin/entrypoint.sh: line 69: syntax error near unexpected token `elif'

My assumption is that i do not provide a SUBFOLDER as 6th argument and therefore the scripts breaks. I want to run the EGW in the root path, that is why I do not provide a SUBFOLDER.

**Comment by sneakyx** [comment]
Oh, sorry didn't see that error. When using an if there must be a line before using an elif.
When the docker image is build, please donload and try again.

**Comment by dawnstrider** [comment]
OK I will. How can I see when the build process is running/completed?

**Comment by sneakyx** [comment]
Hi,
usually 5 -10 Minutes after my update the build process is ready (on docker).
Should be finished by now

**Comment by dawnstrider** [comment]
Re-tested steps in OP. Container is starting correctly.

However I have a new problem. I try to access the website at 'http://MACHINE-IP:4321' and get thrown to a default page of the apache httpd daemon.

Since I provided no subfolder, I expect to see the egroupware page at that location. If I enter 'http://MACHINE-IP:4321/egroupware' I get to the setup screen. There seems to be a problem with the subfolder. Should I create a new ticket?

**Comment by sneakyx** [comment]
plz see my answer in new issue
